export const SET_FIRSTNAME = 'SET_FIRSTNAME';
export const SET_LASTNAME = 'SET_LASTNAME';
export const SET_PROFESSION = 'SET_PROFESSION';
export const SELECT_PROFESSION = 'SELECT_PROFESSION';
export const SET_PHONECODE = 'SET_PHONECODE';
export const SET_PHONENUMBER = 'SET_PHONENUMBER';
